# Generated by Django 3.1.6 on 2021-02-05 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('time', models.TextField(default='')),
                ('ip', models.TextField(default='')),
                ('url', models.TextField(default='')),
                ('action', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='full_log',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('content', models.TextField(default='', verbose_name='content')),
                ('log_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.log')),
            ],
        ),
    ]
