# Generated by Django 3.1.6 on 2021-02-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('content', models.TextField(default='', verbose_name='content')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('action', models.TextField(default='', verbose_name='action')),
            ],
        ),
    ]
